CC=clang++
TARGET_DIR=out
CCFLAGS=-Wall

11: 11_IOManips.cpp
	$(CC) $^ -o $(TARGET_DIR)/$@ $(CCFLAGS)

10: 10_IOFormat.cpp
	$(CC) $^ -o $(TARGET_DIR)/$@ $(CCFLAGS)

03: 03_MyDate.cpp 03_Ostream.cpp
	$(CC) $^ -o $(TARGET_DIR)/$@ $(CCFLAGS)